name    'puppet-puma'
version '0.0.1'
source  'https://github.com/leoc/puppet-puma'
author  'Arthur Leonard Andersen'
license 'GPLv3'
summary 'Puppet Puma Module'
description 'Module to install Rack/Rails applications via puma using puppet'
project_page 'https://github.com/leoc/puppet-puma/'
dependency 'puppetlabs/mysql', '>= 0.6.1'
